#!/usr/bin/env bash

# Description: Import selected files in a beets library.
#
# Shell: NON POSIX compliant
# Author: Stéphane Gleizes

source "$(dirname "$0")"/.nnn-plugin-helper

printf "(s)election/(c)urrent? [default=c] "
read -r resp

if [ "$resp" = "s" ]; then
  readarray -t files < <(tr '\0' '\n' <"$selection")
  set -- "${files[@]}"
else
  set -- "$1"
fi

beet import -m "$@"
