#
# This file is sourced by `bash` login shells.
# It is read after /etc/profile.
#

# Source xsh or error out explicitly.
source "${XSH_DIR:-$HOME/.xsh}/xsh.sh" || return 1

xsh runcom env
xsh runcom login

# Bash does not read ~/.bashrc in a login shell even if it is interactive.
[[ $- == *i* ]] && xsh runcom interactive
