#
# Configuration of the main music library for beets.
#

# Library paths and structure

library: ~/.local/share/beets/library.db
directory: ~/Audios/Musique

per_disc_numbering: no
original_date: no
artist_credit: no
va_name: Various Artists
art_filename: cover

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: $artist/Singles/$title
  comp: Various Artists/$album%aunique{}/$track $title

# Library import options

import:
  write: yes
  move: no
  languages: [fr, en]

# Listing options

format_item: $artist - $album - $title
format_album: $albumartist - $album
time_format: "%Y-%m-%d %H:%M:%S"
sort_album: albumartist+ album+
sort_item: artist+ album+ disc+ track+
sort_case_insensitive: yes

# User interface options

ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: darkyellow
    text_highlight_minor: darkgray
    action_default: cyan
    action: darkblue

# Plugins configuration

plugins:
  - discogs
  - bandcamp
  - info
  - edit
  - duplicates
  - missing
  - lastgenre
  - fetchart
  - mbsync
  - convert
  - playlist
  - smartplaylist
  - play

bandcamp:
  art: yes

fetchart:
  auto: yes
  maxwidth: 1024
  sources:
    - filesystem
    - coverart
    - bandcamp
    - itunes
    - amazon
    - albumart
    - wikipedia

convert:
  album_art_maxwidth: 512
  never_convert_lossy_files: yes

playlist:
  auto: yes
  relative_to: playlist
  playlist_dir: ~/Audios/Playlists

smartplaylist:
  auto: yes
  relative_to: ~/Audios/Playlists/Genre
  playlist_dir: ~/Audios/Playlists/Genre
  playlists:
    # - name: "Newest.m3u"
    #   query: ["added:-17w.. added- artist+ album+ track+"]
    - name: "Metal - Grindcore - Deathcore.m3u"
      query: ["'genre::(Metal|Grindcore|Deathcore)' genre+ artist+ album+ track+"]
    - name: "Goa - Trance - Full On.m3u"
      query: ["'genre::(Goa|Trance|Full On)' genre+ artist+ album+ track+"]
    - name: "Techno - Minimal - House - IDM.m3u"
      query: ["'genre::(Techno|Minimal|House|Idm)' genre+ artist+ album+ track+"]
    - name: "Rock - Pop - Grunge.m3u"
      query: ["'genre::(Rock|Pop|Grunge)' genre+ artist+ album+ track+"]
    - name: "Funk - Soul - Disco.m3u"
      query: ["'genre::(Funk|Soul|Disco)' genre+ artist+ album+ track+"]
    - name: "Jazz - Blues - Afrobeat.m3u"
      query: ["'genre::(Jazz|Blues|Afrobeat)' genre+ artist+ album+ track+"]
    - name: "Reggae - Dub - Ska.m3u"
      query: ["'genre::(Reggae|Dub|Ska)' genre+ artist+ album+ track+"]
    - name: "Dubstep - D&B - Breakbeat.m3u"
      query: ["'genre::(Dubstep|Drum And Bass|Breakbeat)' genre+ artist+ album+ track+"]
    - name: "Rap - Hip Hop - Chanson.m3u"
      query: ["'genre::(Rap|Hip Hop|Chanson)' genre+ artist+ album+ track+"]
    - name: "Trip-Hop - Electro-Swing.m3u"
      query: ["'genre::(Trip-Hop|Electro-swing)' genre+ artist+ album+ track+"]
    - name: "Ambient - Chillout - Downtempo.m3u"
      query: ["'genre::(Ambient|Chillout|Downtempo)' genre+ artist+ album+ track+"]
    - name: "Classical - New Age.m3u"
      query: ["'genre::(Classical|New Age)' genre+ artist+ album+ track+"]
    - name: "Breakcore - Hardcore - Gabber.m3u"
      query: ["'genre::(Breakcore|Hardcore|Gabber)' genre+ artist+ album+ track+"]
    - name: "Experimental - Avant-Garde.m3u"
      query: ["'genre::(Experimental|Avant-Garde)' genre+ artist+ album+ track+"]
    - name: "Electronic (various).m3u"
      query: ["'genre::(Electro|Electronic|New Rave|Turntablism)' genre+ artist+ album+ track+"]

play:
  command: strawberry --play --create=Beets
  raw: yes
